### ISSUE TITLE
Using <dialog> as base

### ISSUE THREAD

**Issue by simevidas** [zewish/rmodal.js#1]
Have you considered using the standard `<dialog>` element as a base? It is already supported in Blink-based browsers.

**Comment by zewish** [comment]
Thanks for the heads up - I'm always open to suggestions. I'm not sure I can answer this question before I'm finished reading the documentation for the `<dialog>` tag. Let me come back to you later.

**Comment by zewish** [comment]
I won't be using `<dialog>` elements as a base for now. Not until it's mainstream and it starts working in all major browsers. I found a polyfill but it's size is huge compared to this component - that's the other problem.
