### ISSUE TITLE
<SELECT> options are removed when modal dialog is not shown at first

### ISSUE THREAD

**Issue by jaimestuardo** [zewish/rmodal.js#10]
This is strange....

In order to reproduce the problem, you can use this code:

`< div class="modal" >
    < select >< option >Hello< /option >< /select >
< /div >`

The page will be rendered a (you will need to see this in Firebug, because when viewing page source, the code above will be displayed)

`< div class="modal" >
    < select >< /select >
< /div >`

If I comment JavaScript instruction that converts the DIV into RModal out, the SELECT option appears. It is strange, isn't it?

If you does not comment the JavaScript out, but change the "display" attribute to "block", so that the dialog appears initially visible, the option is shown too.

Please check it.

EDIT:

When the page loads, and see the source with Firebug, the option is still there, but, when modal is shown, using open() method, all options are gone.

Thanks

**Comment by zewish** [comment]
Hey there @jaimestuardo, I see that you closed the issue.
Did you find a solution to your problem?
