### ISSUE TITLE
Content may be hidden because modals have a fixed width

### ISSUE THREAD

**Issue by not-a-lot** [zewish/rmodal.js#12]
Hi, I recently went from Bootstrap modals to rmodal because I didn’t like Bootstrap’s bloated CSS, and I like rmodal a lot, but noticed an issue that doesn’t happen with Bootstrap modals : when you for example pin the web browser window to one half of the screen, or when you zoom, with Bootstrap the modals have a maximal width that doesn’t overflow the viewport, whereas with rmodal, the modals may easily become too large and the right part of their content is then invisible (there is no horizontal scroll bar either)

**Comment by zewish** [comment]
Should be quite easy to fix with a bit of CSS. Feel free to make a pull request.

**Comment by not-a-lot** [comment]
Thank you for your answer :) I haven’t taken the time to understand how everything works yet, but I found a way of fixing it. You were right that it's easy, the problem comes from the width of `.modal .modal-fixed`, which is fixed to `1100px` no matter the width of the viewport. By comparison, Bootstrap uses `width: auto;` and a (horizontal) margin of `10px`, and in addition to that, it has a media query if the `min-width` is `768px` :

```css
@media (min-width: 768px) {
  .modal-dialog {
    width: 600px;
    margin: 30px auto;
  }
  …
}
```
I don’t know what you would prefer? A percentage value instead of `1100px` also works. But it might be desirable to take more or less space depending on the width of the viewport
