### ISSUE TITLE
Wrong demo link

### ISSUE THREAD

**Issue by aarongarciah** [zewish/rmodal.js#17]
Hi! The link to the Plunker demo in the README.md seems to be wrong. Also in https://rmodal.js.org/ 

<img width="1792" alt="Screenshot of error in Plunker when opening" src="https://user-images.githubusercontent.com/7225802/40600937-75f2afd4-6253-11e8-848b-ad5711f66a50.png">

Thanks!

**Comment by zewish** [comment]
Hi, @aarongarciah. Please disable your ad blocker.
The demo link is correct ;)

**Comment by aarongarciah** [comment]
Now it works. But I haven't disabled my ad blocker 🤔 Thanks

**Comment by zewish** [comment]
Could just be plunker being down at the time of your first comment.
