### ISSUE TITLE
Close modal when click on backdrop area

### ISSUE THREAD

**Issue by didiraja** [zewish/rmodal.js#18]
Awesome plugin, is really annoying using powerful libs just to popup a simple modal. 

That said, I missed that default interaction to click outside the modal and close it. For some users, that is a default behavior. After that, probably a perfect modal lib.

Keep the good job.

**Comment by zewish** [comment]
Hey there!
Glad you like the library.

You can see how to make the modal close when the user clicks on the overlay:
https://github.com/zewish/rmodal.js/issues/5

Cheers,
Iskren.
