### ISSUE TITLE
Modal does not capture keyboard focus

### ISSUE THREAD

**Issue by bighuggies** [zewish/rmodal.js#2]
When the modal is displayed, keyboard focus should move either to the dialog element itself or to the first form control.

While the modal is displayed, the user can still interact with elements behind the modal using the keyboard.

**Comment by zewish** [comment]
Now you can change the default element that's focussed when the dialog is shown:
```
var modal = new RModal{{
    focus: ['selectors', 'prioritized', 'by', 'order']

    // or:
    focus: false // if you don't need elements focussed

    // or:
    focus: [] // to use firstChild element of dialog element

    // these are the defaults if the focus option is undefined:
    // ['input', 'select', 'textarea', 'button']
});
```

The focus of the last active element before the modal is shown is restored when the dialog is closed. If you want to override this you use the "beforeClose" hook:

```
var modal = new RModal{{
    focus: 'input.my-first-input'
    beforeClose: function(next) {
        modal.focusOutElement = document.getElementById("element-to-focus-after-close");
        next();
    }
});
```

There are two new functions that are exported - element() and focus():
- The element() function returns the first HTMLElement (or null) found using querySelector() on the dialog element. You may pass a string or an array as the "selector" parameter.
- The focus() function takes an HTMLElement as a parameter and tries to focus the element.
