### ISSUE TITLE
dialogCloseClass does NOT remove dialogOpenClass

### ISSUE THREAD

**Issue by grgg7** [zewish/rmodal.js#21]
Hi everyone. I would like to first thank you for the awesome work you put into this lightweight modal plugin. It's very versatile (for me at least) and I love how it integrates with animate.css.

I found a problem - when use `dialogOpenClass: 'animated zoomIn'` and then you use `dialogCloseClass: 'animated zoomOut'`, everything works fine. But when you try to open the modal again, the modal doesn't show up because the old classes still remain for those elements - in this case, `fadeIn` and `fadeOut` still exists, as you can see via Inspect Element.

Here is an example: http://next.plnkr.co/edit/1xszc0nNrAsPLm7G
Click on "Show modal" and then click on "Close". Then try to to click on "Show modal" again and you will see that the modal doesn't actually show up. If you inspect the element, you can see that the old animate classes are still there.

**Comment by zewish** [comment]
Hi, unfortunately it only works with a single class for now.
You need to specify the following and it should work the way you want to: 

```js
{
     dialogClass: 'animated',
     dialogOpenClass: 'zoomIn',
     dialogCloseClass: 'zoomOut'
}
```
This would probably be fixed in the next release.

**Comment by edwardjiang7** [comment]
Here's what I've been doing that's a working solution for me:

Use `removeClass()` in `afterOpen`:
```
afterOpen: function() {
	$("#modal > div.modal-dialog").removeClass("zoomOut")
}
```

and do the same thing for `afterClose`:
```
afterClose: function() {
	$("#modal > div.modal-dialog").removeClass("zoomIn")
}
```
