### ISSUE TITLE
RModal is not defined on website using RequireJS

### ISSUE THREAD

**Issue by marcin-synak** [zewish/rmodal.js#22]
I have a script which dynamically loads rmodal.min.js on my clients' websites and then tries to show a popup as usual.

It looks somewhat like this:

    (function() {
        // this piece loads rmodal.min.js
        var d = document, g = d.createElement('script');
        g.type = 'text/javascript'; g.async = false; g.defer = true; g.src = 'somepath/rmodal.min.js';
        d.head.appendChild(g);

        // this piece waits for the script to load and creates a popup
        g.onload = function() {
            var popup = new RModal(document.getElementById('myPopup'));
            popup.open();
        };
    }();

Usually it works very well. However, I encountered a website that uses RequireJS v2.1.2 library. RModal detects this and tries to load itself using "define" function. Obviously it fails somehow, since then I get an JS error when trying to create a popup (or just check for the RModal in the console):

    ReferenceError: RModal is not defined

The method of loading the script is not an issue, it might as well be static <script> tag in HEAD. I even tried manually running the whole rmodal.min.js script through browser's console.

If I simply comment the lines in rmodal.min.js that are responsible for define/AMD support, everything works fine, since initialization is done using default fallback method. I'm talking about these lines of code:

	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.RModal = factory());

Am I doing something wrong here? Is it an error to expect that RModal / window.RModal object will be defined no matter how the library was initialized?
I'm not familiar with RequireJS and have no need for it - it was a random interaction between my script and other scripts on client's website.

I'd rather not make changes in rmodal.min.js (since it is an external library), so maybe there's some workaround?

**Comment by zewish** [comment]
If you're using AMD on your website you need to import RModal using AMD itself. The exports are generated in such a way that an AMD export is used if found.

**Comment by zewish** [comment]
If the website is using RequireJS then you need to import RModal using RequireJS itself. The library supports such exports, so you should have no issues if you import it using the already existing module loading mechanism on the website.

**Comment by marcin-synak** [comment]
Thanks, that's what I did in the end. I detect whether RequireJS is available and use it to load RModal. If not, the default method is used. It looks somewhat like this:

```js
if (typeof define === 'function' && define.amd) {
    // fix for websites using requirejs
    require(['somepath/rmodal.min.js'], function(rmodal) {
        window.RModal = rmodal;
        buildPopup();
    });
} else {
    // regular script loading method
    var d = document, g = d.createElement('script');
    g.type = 'text/javascript'; g.async = false; g.defer = true; g.src = 'somepath/rmodal.min.js';
    d.head.appendChild(g);
    g.onload = buildPopup;
}
```

It just took me a while since I've never encountered RequireJS before and docs for RModal only mention it is supported, not how to use it in such environment.

Eh, writing panzercode is not easy ;)
