### ISSUE TITLE
A simple modal dialog with no external dependencies

### ISSUE THREAD

**Issue by eduardoroyer** [zewish/rmodal.js#6]
The title say that doesn't have dependencies. But, I need bootstrap and animate to work?

**Comment by zewish** [comment]
No, you don't need bootstrap.css or animate.css - these are optional extras, you can use the modal without.

Take a look at the rmodal.css. You can add `class="no-bootstrap"` to the `<body>` element and you can remove them completely.

**Comment by eduardoroyer** [comment]
I asked because I'm putting in a angular directive.

Thanks []

**Comment by zewish** [comment]
I actually had a plan to create an angular.js directive, but I haven't got time for now. I currently have two different directives, using different approaches that aren't as feature rich as the dialog itself. So I'm glad that someone took the time to do this instead of me. Have fun! :smiley:

**Comment by eduardoroyer** [comment]
If you want to take a look and maybe help or disclose. Here is the repository: https://github.com/eduardoroyer/angular-rmodal
