### ISSUE TITLE
[Question] wouldn't be nicer to have a great replacement for BS modal?

### ISSUE THREAD

**Issue by thednp** [zewish/rmodal.js#7]
I am writing a native javascript module for Bootstrap modal and I am reading your code and came to thinking.. instead of some unwanted and mostly unnecessary scripting for focusing text inputs or other stuff, why not have a perfect replacement for Bootstrap modal?

**Comment by zewish** [comment]
Bootstrap's modal.js actually has the focus feature builtin - you can check their demo page for reference.

The idea of rmodal.js has always been to be as small and as lean as possible, with no external dependencies, without loosing functionality.

Bootstrap's great, but it's not feasible for all types of projects. Somebody would probably like to use rmodal.js with Foundation, Pure or another CSS framework.

I wouldn't be happy if the users are obliged to use one framework vendor only.
